### ISSUE TITLE
Add display page for reporting solar charge controller information

### ISSUE THREAD

**Issue by icr-ctl** [icr-ctl/dencam#17]
We'll do this in steps.  The eventual goal of the issue is to add a page that reports particular data pulled from the SunSaver charge controller.  But first let's just get a stand-in page implemented into the system with some random stand-in text (and then later connect with Kyra for her code that talks to the SunSaver and bring that code into the mix).

**Comment by bkirshh** [comment]
Power Status Screen 

I would suggest this page within dencam.py would allow operators to check power related values captured from the MPPT Charge Controller via ModBus. The values below would be helpful within the power status page...

Desired Values to display
SunSaver MPPT Battery Voltage (V)	
SunSaver MPPT Array Voltage (V)	
SunSaver MPPT Charge Current (A)	
SunSaver MPPT Load Current (A)

Optional if additional space is available
SunSaver MPPT Ah Charge(Daily) (Ah)	
SunSaver MPPT Ah Load(Daily) (Ah)
