### ISSUE TITLE
Airplane Mode

### ISSUE THREAD

**Issue by bkirshh** [icr-ctl/dencam#20]
Airplane Mode
Option within YAML file for Pi to boot into “Airplane Mode”. Airplane mode would disable wireless services (Wifi Off, Bluetooth Off) to conserve power.

It would be great to also have one of the status pages allow for a button within Dencam.py to turn "Airplane Mode" off/on. The toggling of the button would temporarily change the state of "Airplane Mode" but that setting would only hold until the pi reboots at midnight. After reboot, the YAML entry would dictate the state of "Airplane Mode".

**Comment by icr-ctl** [comment]
If I gathered correctly from verbal conversations with folks earlier today, there was a question about whether/how to integrate this into the main dencam program.  I would argue that, yes, we do want to integrate it, especially given the requirements BJ outlined above. If I understood correctly, the solutions that were found involve running external commands on the CLI.  If that is the case, I would suggest using the subprocess module to invoke these commands in the appropriate place/way within DenCam.
