### ISSUE TITLE
Dencam crashes when recording size is greater than storage available

### ISSUE THREAD

**Issue by iamgarcia** [icr-ctl/dencam#42]
While testing the storage behavior, I ran into a major issue. The issue occurs when the recording size is greater than the storage available. This results in the system crashing. Currently figuring out ways to handle the issue of recordings starting before the storage limit check.

![unknown](https://user-images.githubusercontent.com/32944795/151738236-71216ee9-6f38-4bf1-ae16-e60ea85c5904.png)

A potential solution might be to check if the estimated recording file size is greater than the available storage.

**Comment by icr-ctl** [comment]
I think there are a few solution ideas that you (Alex) have in the mix that we haven't documented here but @tkswanson did just bring up the idea of somehow reserving space on the main SD card independent of the main dencam code's awareness.  Solutions in this space might include for instance having a partition on the disk that the main code "doesn't know about" or can't access.  A con of that particular version of this idea might be the requirement that someone partition things appropriately etc. but it does feel as if maybe there is a lower-hanging fruit thing we could do in this vein.

I also think that once we know what sorts of file-sizes BJ was getting per video we might be able to just set the threshold with a very high safety factor (maybe even 10x) and be fine.
