### ISSUE TITLE
Drive Status Page Flash

### ISSUE THREAD

**Issue by bkirshh** [icr-ctl/dencam#44]
After reboot, when a user presses the 1st GPIO button to turn on the screen, the second status screen (blue showing "Vids This Run...) briefly shows first before the typical 1st page (red showing device name). After running through the entire suite of status pages, this bug does not repeat until after reboot.

**Comment by icr-ctl** [comment]
Did BJ say somewhere that this was still an issue?  It also sounded as if there was a chance that his units were still running a version from before this fix was merged, right? If someone knows the situation on this, please comment here so we can decide if this is truly resolved.
